// Mocks generated by Mockito from annotations
// in data/test/functionality_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:data/data.dart' as _i2;
import 'package:data/src/network/model/functionality/functionality_dto.dart'
    as _i10;
import 'package:data/src/network/model/request/copy_body_request.dart' as _i9;
import 'package:data/src/network/model/request/share_document_body_request.dart'
    as _i8;
import 'package:data/src/network/model/response/account_quota_response.dart'
    as _i4;
import 'package:data/src/network/model/response/user_response.dart' as _i7;
import 'package:dio/dio.dart' as _i3;
import 'package:domain/domain.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePermanentToken_0 extends _i1.SmartFake
    implements _i2.PermanentToken {
  _FakePermanentToken_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseBody_1 extends _i1.SmartFake implements _i3.ResponseBody {
  _FakeResponseBody_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentResponse_2 extends _i1.SmartFake
    implements _i2.DocumentResponse {
  _FakeDocumentResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkGroupNodeDto_3 extends _i1.SmartFake
    implements _i2.WorkGroupNodeDto {
  _FakeWorkGroupNodeDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountQuotaResponse_4 extends _i1.SmartFake
    implements _i4.AccountQuotaResponse {
  _FakeAccountQuotaResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedSpaceNodeNestedResponse_5 extends _i1.SmartFake
    implements _i2.SharedSpaceNodeNestedResponse {
  _FakeSharedSpaceNodeNestedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeWorkGroupNodeFolderDto_6 extends _i1.SmartFake
    implements _i2.WorkGroupNodeFolderDto {
  _FakeWorkGroupNodeFolderDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedSpaceMemberResponse_7 extends _i1.SmartFake
    implements _i2.SharedSpaceMemberResponse {
  _FakeSharedSpaceMemberResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentDetailsResponse_8 extends _i1.SmartFake
    implements _i2.DocumentDetailsResponse {
  _FakeDocumentDetailsResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadRequestGroupResponse_9 extends _i1.SmartFake
    implements _i2.UploadRequestGroupResponse {
  _FakeUploadRequestGroupResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadRequestResponse_10 extends _i1.SmartFake
    implements _i2.UploadRequestResponse {
  _FakeUploadRequestResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReceivedShareDto_11 extends _i1.SmartFake
    implements _i2.ReceivedShareDto {
  _FakeReceivedShareDto_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadRequestEntryResponse_12 extends _i1.SmartFake
    implements _i2.UploadRequestEntryResponse {
  _FakeUploadRequestEntryResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LinShareHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinShareHttpClient extends _i1.Mock
    implements _i2.LinShareHttpClient {
  MockLinShareHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PermanentToken> createPermanentToken(
    Uri? authenticateUrl,
    _i6.APIVersionSupported? apiVersion,
    String? userName,
    String? password,
    _i2.PermanentTokenBodyRequest? bodyRequest, {
    _i6.OTPCode? otpCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPermanentToken,
              [authenticateUrl, apiVersion, userName, password, bodyRequest],
              {#otpCode: otpCode},
            ),
            returnValue: _i5.Future<_i2.PermanentToken>.value(
              _FakePermanentToken_0(
                this,
                Invocation.method(
                  #createPermanentToken,
                  [
                    authenticateUrl,
                    apiVersion,
                    userName,
                    password,
                    bodyRequest,
                  ],
                  {#otpCode: otpCode},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PermanentToken>);

  @override
  _i5.Future<_i2.PermanentToken> createPermanentTokenWithOIDC(
    Uri? authenticateUrl,
    _i6.APIVersionSupported? apiVersion,
    _i6.TokenOIDC? oidcToken,
    _i2.PermanentTokenBodyRequest? bodyRequest, {
    _i6.OTPCode? otpCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPermanentTokenWithOIDC,
              [authenticateUrl, apiVersion, oidcToken, bodyRequest],
              {#otpCode: otpCode},
            ),
            returnValue: _i5.Future<_i2.PermanentToken>.value(
              _FakePermanentToken_0(
                this,
                Invocation.method(
                  #createPermanentTokenWithOIDC,
                  [authenticateUrl, apiVersion, oidcToken, bodyRequest],
                  {#otpCode: otpCode},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PermanentToken>);

  @override
  _i5.Future<bool> deletePermanentToken(_i2.PermanentToken? token) =>
      (super.noSuchMethod(
            Invocation.method(#deletePermanentToken, [token]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i7.UserResponse?> getAuthorizedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthorizedUser, []),
            returnValue: _i5.Future<_i7.UserResponse?>.value(),
          )
          as _i5.Future<_i7.UserResponse?>);

  @override
  _i5.Future<List<_i2.DocumentResponse>> getAllDocument() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDocument, []),
            returnValue: _i5.Future<List<_i2.DocumentResponse>>.value(
              <_i2.DocumentResponse>[],
            ),
          )
          as _i5.Future<List<_i2.DocumentResponse>>);

  @override
  _i5.Future<List<_i2.ShareDto>> shareDocument(
    _i8.ShareDocumentBodyRequest? bodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shareDocument, [bodyRequest]),
            returnValue: _i5.Future<List<_i2.ShareDto>>.value(<_i2.ShareDto>[]),
          )
          as _i5.Future<List<_i2.ShareDto>>);

  @override
  _i5.Future<_i3.ResponseBody> downloadFile(
    String? url,
    _i3.CancelToken? cancelToken,
    _i6.Token? permanentToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [
              url,
              cancelToken,
              permanentToken,
            ]),
            returnValue: _i5.Future<_i3.ResponseBody>.value(
              _FakeResponseBody_1(
                this,
                Invocation.method(#downloadFile, [
                  url,
                  cancelToken,
                  permanentToken,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.ResponseBody>);

  @override
  _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>> getSharedSpaces() =>
      (super.noSuchMethod(
            Invocation.method(#getSharedSpaces, []),
            returnValue:
                _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>>.value(
                  <_i2.SharedSpaceNodeNestedResponse>[],
                ),
          )
          as _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>>);

  @override
  _i5.Future<List<_i2.AuditLogEntryUserDto?>> getSharedSpaceActivities(
    _i6.SharedSpaceId? sharedSpaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedSpaceActivities, [sharedSpaceId]),
            returnValue: _i5.Future<List<_i2.AuditLogEntryUserDto?>>.value(
              <_i2.AuditLogEntryUserDto?>[],
            ),
          )
          as _i5.Future<List<_i2.AuditLogEntryUserDto?>>);

  @override
  _i5.Future<List<_i6.AutoCompleteResult>> getSharingAutoComplete(
    _i6.AutoCompletePattern? autoCompletePattern,
    _i6.AutoCompleteType? autoCompleteType, {
    _i6.ThreadId? threadId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSharingAutoComplete,
              [autoCompletePattern, autoCompleteType],
              {#threadId: threadId},
            ),
            returnValue: _i5.Future<List<_i6.AutoCompleteResult>>.value(
              <_i6.AutoCompleteResult>[],
            ),
          )
          as _i5.Future<List<_i6.AutoCompleteResult>>);

  @override
  _i5.Future<List<_i2.WorkGroupNodeDto>> getWorkGroupChildNodes(
    _i6.SharedSpaceId? sharedSpaceId, {
    _i6.WorkGroupNodeId? parentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWorkGroupChildNodes,
              [sharedSpaceId],
              {#parentId: parentId},
            ),
            returnValue: _i5.Future<List<_i2.WorkGroupNodeDto>>.value(
              <_i2.WorkGroupNodeDto>[],
            ),
          )
          as _i5.Future<List<_i2.WorkGroupNodeDto>>);

  @override
  _i5.Future<List<_i6.ReceivedShare>> getReceivedShares() =>
      (super.noSuchMethod(
            Invocation.method(#getReceivedShares, []),
            returnValue: _i5.Future<List<_i6.ReceivedShare>>.value(
              <_i6.ReceivedShare>[],
            ),
          )
          as _i5.Future<List<_i6.ReceivedShare>>);

  @override
  _i5.Future<List<_i2.WorkGroupNodeDto>>
  copyWorkGroupNodeToSharedSpaceDestination(
    _i9.CopyBodyRequest? copyRequest,
    _i6.SharedSpaceId? destinationSharedSpaceId, {
    _i6.WorkGroupNodeId? destinationParentNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #copyWorkGroupNodeToSharedSpaceDestination,
              [copyRequest, destinationSharedSpaceId],
              {#destinationParentNodeId: destinationParentNodeId},
            ),
            returnValue: _i5.Future<List<_i2.WorkGroupNodeDto>>.value(
              <_i2.WorkGroupNodeDto>[],
            ),
          )
          as _i5.Future<List<_i2.WorkGroupNodeDto>>);

  @override
  _i5.Future<_i2.DocumentResponse> removeDocument(_i6.DocumentId? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDocument, [documentId]),
            returnValue: _i5.Future<_i2.DocumentResponse>.value(
              _FakeDocumentResponse_2(
                this,
                Invocation.method(#removeDocument, [documentId]),
              ),
            ),
          )
          as _i5.Future<_i2.DocumentResponse>);

  @override
  _i5.Future<_i2.DocumentResponse> renameDocument(
    _i6.DocumentId? documentId,
    _i6.RenameDocumentRequest? renameDocumentRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameDocument, [
              documentId,
              renameDocumentRequest,
            ]),
            returnValue: _i5.Future<_i2.DocumentResponse>.value(
              _FakeDocumentResponse_2(
                this,
                Invocation.method(#renameDocument, [
                  documentId,
                  renameDocumentRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.DocumentResponse>);

  @override
  _i5.Future<_i2.WorkGroupNodeDto> removeSharedSpaceNode(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.WorkGroupNodeId? sharedSpaceNodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeSharedSpaceNode, [
              sharedSpaceId,
              sharedSpaceNodeId,
            ]),
            returnValue: _i5.Future<_i2.WorkGroupNodeDto>.value(
              _FakeWorkGroupNodeDto_3(
                this,
                Invocation.method(#removeSharedSpaceNode, [
                  sharedSpaceId,
                  sharedSpaceNodeId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.WorkGroupNodeDto>);

  @override
  _i5.Future<_i4.AccountQuotaResponse> findQuota(_i6.QuotaId? quotaUuid) =>
      (super.noSuchMethod(
            Invocation.method(#findQuota, [quotaUuid]),
            returnValue: _i5.Future<_i4.AccountQuotaResponse>.value(
              _FakeAccountQuotaResponse_4(
                this,
                Invocation.method(#findQuota, [quotaUuid]),
              ),
            ),
          )
          as _i5.Future<_i4.AccountQuotaResponse>);

  @override
  _i5.Future<List<_i2.DocumentResponse>> copyToMySpace(
    _i9.CopyBodyRequest? copyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyToMySpace, [copyRequest]),
            returnValue: _i5.Future<List<_i2.DocumentResponse>>.value(
              <_i2.DocumentResponse>[],
            ),
          )
          as _i5.Future<List<_i2.DocumentResponse>>);

  @override
  _i5.Future<List<_i10.FunctionalityDto>> getAllFunctionality() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFunctionality, []),
            returnValue: _i5.Future<List<_i10.FunctionalityDto>>.value(
              <_i10.FunctionalityDto>[],
            ),
          )
          as _i5.Future<List<_i10.FunctionalityDto>>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> deleteSharedSpace(
    _i6.SharedSpaceId? sharedSpaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedSpace, [sharedSpaceId]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#deleteSharedSpace, [sharedSpaceId]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.WorkGroupNodeFolderDto> createSharedSpaceNodeFolder(
    _i6.SharedSpaceId? sharedSpaceId,
    _i2.CreateSharedSpaceNodeFolderRequest? createSharedSpaceNodeRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSharedSpaceNodeFolder, [
              sharedSpaceId,
              createSharedSpaceNodeRequest,
            ]),
            returnValue: _i5.Future<_i2.WorkGroupNodeFolderDto>.value(
              _FakeWorkGroupNodeFolderDto_6(
                this,
                Invocation.method(#createSharedSpaceNodeFolder, [
                  sharedSpaceId,
                  createSharedSpaceNodeRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.WorkGroupNodeFolderDto>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> getSharedSpace(
    _i6.SharedSpaceId? sharedSpaceId, {
    _i6.MembersParameter? membersParameter = _i6.MembersParameter.withMembers,
    _i6.RolesParameter? rolesParameter = _i6.RolesParameter.withRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSharedSpace,
              [sharedSpaceId],
              {
                #membersParameter: membersParameter,
                #rolesParameter: rolesParameter,
              },
            ),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(
                  #getSharedSpace,
                  [sharedSpaceId],
                  {
                    #membersParameter: membersParameter,
                    #rolesParameter: rolesParameter,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<List<_i2.SharedSpaceMemberResponse>> getSharedSpaceMembers(
    _i6.SharedSpaceId? sharedSpaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedSpaceMembers, [sharedSpaceId]),
            returnValue: _i5.Future<List<_i2.SharedSpaceMemberResponse>>.value(
              <_i2.SharedSpaceMemberResponse>[],
            ),
          )
          as _i5.Future<List<_i2.SharedSpaceMemberResponse>>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> createSharedSpaceWorkGroup(
    _i2.CreateWorkGroupBodyRequest? createWorkGroupBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSharedSpaceWorkGroup, [
              createWorkGroupBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#createSharedSpaceWorkGroup, [
                  createWorkGroupBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.WorkGroupNodeDto> renameSharedSpaceNode(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.WorkGroupNodeId? sharedSpaceNodeId,
    _i2.RenameWorkGroupNodeBodyRequest? renameWorkGroupNodeBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameSharedSpaceNode, [
              sharedSpaceId,
              sharedSpaceNodeId,
              renameWorkGroupNodeBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.WorkGroupNodeDto>.value(
              _FakeWorkGroupNodeDto_3(
                this,
                Invocation.method(#renameSharedSpaceNode, [
                  sharedSpaceId,
                  sharedSpaceNodeId,
                  renameWorkGroupNodeBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.WorkGroupNodeDto>);

  @override
  _i5.Future<_i2.SharedSpaceMemberResponse> addSharedSpaceMember(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.AddSharedSpaceMemberRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSharedSpaceMember, [sharedSpaceId, request]),
            returnValue: _i5.Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7(
                this,
                Invocation.method(#addSharedSpaceMember, [
                  sharedSpaceId,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceMemberResponse>);

  @override
  _i5.Future<List<_i2.SharedSpaceRoleDto>> getSharedSpaceRoles({
    _i6.LinShareNodeType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedSpaceRoles, [], {#type: type}),
            returnValue: _i5.Future<List<_i2.SharedSpaceRoleDto>>.value(
              <_i2.SharedSpaceRoleDto>[],
            ),
          )
          as _i5.Future<List<_i2.SharedSpaceRoleDto>>);

  @override
  _i5.Future<_i2.SharedSpaceMemberResponse> updateRoleSharedSpaceMember(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.UpdateSharedSpaceMemberRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoleSharedSpaceMember, [
              sharedSpaceId,
              request,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7(
                this,
                Invocation.method(#updateRoleSharedSpaceMember, [
                  sharedSpaceId,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceMemberResponse>);

  @override
  _i5.Future<_i2.SharedSpaceMemberResponse> updateRoleDriveMember(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.UpdateDriveMemberRequest? request, {
    bool? isOverrideRoleForAll,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRoleDriveMember,
              [sharedSpaceId, request],
              {#isOverrideRoleForAll: isOverrideRoleForAll},
            ),
            returnValue: _i5.Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7(
                this,
                Invocation.method(
                  #updateRoleDriveMember,
                  [sharedSpaceId, request],
                  {#isOverrideRoleForAll: isOverrideRoleForAll},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceMemberResponse>);

  @override
  _i5.Future<_i2.SharedSpaceMemberResponse> updateRoleWorkspaceMember(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.UpdateWorkspaceMemberRequest? request, {
    bool? isOverrideRoleForAll,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRoleWorkspaceMember,
              [sharedSpaceId, request],
              {#isOverrideRoleForAll: isOverrideRoleForAll},
            ),
            returnValue: _i5.Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7(
                this,
                Invocation.method(
                  #updateRoleWorkspaceMember,
                  [sharedSpaceId, request],
                  {#isOverrideRoleForAll: isOverrideRoleForAll},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceMemberResponse>);

  @override
  _i5.Future<_i2.SharedSpaceMemberResponse> deleteSharedSpaceMember(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.SharedSpaceMemberId? sharedSpaceMemberId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedSpaceMember, [
              sharedSpaceId,
              sharedSpaceMemberId,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7(
                this,
                Invocation.method(#deleteSharedSpaceMember, [
                  sharedSpaceId,
                  sharedSpaceMemberId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceMemberResponse>);

  @override
  _i5.Future<_i2.DocumentDetailsResponse> getDocument(
    _i6.DocumentId? documentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDocument, [documentId]),
            returnValue: _i5.Future<_i2.DocumentDetailsResponse>.value(
              _FakeDocumentDetailsResponse_8(
                this,
                Invocation.method(#getDocument, [documentId]),
              ),
            ),
          )
          as _i5.Future<_i2.DocumentDetailsResponse>);

  @override
  _i5.Future<_i2.WorkGroupNodeDto> getWorkGroupNode(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.WorkGroupNodeId? workGroupNodeId, {
    bool? hasTreePath = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWorkGroupNode,
              [sharedSpaceId, workGroupNodeId],
              {#hasTreePath: hasTreePath},
            ),
            returnValue: _i5.Future<_i2.WorkGroupNodeDto>.value(
              _FakeWorkGroupNodeDto_3(
                this,
                Invocation.method(
                  #getWorkGroupNode,
                  [sharedSpaceId, workGroupNodeId],
                  {#hasTreePath: hasTreePath},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.WorkGroupNodeDto>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> renameWorkGroup(
    _i6.SharedSpaceId? sharedSpaceId,
    _i2.RenameWorkGroupBodyRequest? renameWorkGroupBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameWorkGroup, [
              sharedSpaceId,
              renameWorkGroupBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#renameWorkGroup, [
                  sharedSpaceId,
                  renameWorkGroupBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> renameDrive(
    _i6.SharedSpaceId? sharedSpaceId,
    _i2.RenameDriveBodyRequest? renameDriveBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameDrive, [
              sharedSpaceId,
              renameDriveBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#renameDrive, [
                  sharedSpaceId,
                  renameDriveBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> renameWorkSpace(
    _i6.SharedSpaceId? sharedSpaceId,
    _i2.RenameWorkSpaceBodyRequest? bodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameWorkSpace, [sharedSpaceId, bodyRequest]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#renameWorkSpace, [
                  sharedSpaceId,
                  bodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.DocumentResponse> editDescriptionDocument(
    _i6.DocumentId? documentId,
    _i6.EditDescriptionDocumentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editDescriptionDocument, [documentId, request]),
            returnValue: _i5.Future<_i2.DocumentResponse>.value(
              _FakeDocumentResponse_2(
                this,
                Invocation.method(#editDescriptionDocument, [
                  documentId,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.DocumentResponse>);

  @override
  _i5.Future<List<_i2.UploadRequestGroupResponse>> getAllUploadRequestGroups(
    List<_i6.UploadRequestStatus>? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUploadRequestGroups, [status]),
            returnValue: _i5.Future<List<_i2.UploadRequestGroupResponse>>.value(
              <_i2.UploadRequestGroupResponse>[],
            ),
          )
          as _i5.Future<List<_i2.UploadRequestGroupResponse>>);

  @override
  _i5.Future<_i2.UploadRequestGroupResponse> addNewUploadRequest(
    _i6.UploadRequestCreationType? creationType,
    _i6.AddUploadRequest? addUploadRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewUploadRequest, [
              creationType,
              addUploadRequest,
            ]),
            returnValue: _i5.Future<_i2.UploadRequestGroupResponse>.value(
              _FakeUploadRequestGroupResponse_9(
                this,
                Invocation.method(#addNewUploadRequest, [
                  creationType,
                  addUploadRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestGroupResponse>);

  @override
  _i5.Future<List<_i2.UploadRequestResponse>> getAllUploadRequests(
    _i6.UploadRequestGroupId? uploadRequestGroupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUploadRequests, [uploadRequestGroupId]),
            returnValue: _i5.Future<List<_i2.UploadRequestResponse>>.value(
              <_i2.UploadRequestResponse>[],
            ),
          )
          as _i5.Future<List<_i2.UploadRequestResponse>>);

  @override
  _i5.Future<List<_i2.UploadRequestEntryResponse>> getAllUploadRequestEntries(
    _i6.UploadRequestId? uploadRequestId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUploadRequestEntries, [uploadRequestId]),
            returnValue: _i5.Future<List<_i2.UploadRequestEntryResponse>>.value(
              <_i2.UploadRequestEntryResponse>[],
            ),
          )
          as _i5.Future<List<_i2.UploadRequestEntryResponse>>);

  @override
  _i5.Future<_i2.UploadRequestResponse> updateUploadRequestStatus(
    _i6.UploadRequestId? uploadRequestId,
    _i6.UploadRequestStatus? newStatus, {
    bool? copyToMySpace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadRequestStatus,
              [uploadRequestId, newStatus],
              {#copyToMySpace: copyToMySpace},
            ),
            returnValue: _i5.Future<_i2.UploadRequestResponse>.value(
              _FakeUploadRequestResponse_10(
                this,
                Invocation.method(
                  #updateUploadRequestStatus,
                  [uploadRequestId, newStatus],
                  {#copyToMySpace: copyToMySpace},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestResponse>);

  @override
  _i5.Future<_i2.ReceivedShareDto> getReceivedShare(
    _i6.ShareId? receivedShareId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReceivedShare, [receivedShareId]),
            returnValue: _i5.Future<_i2.ReceivedShareDto>.value(
              _FakeReceivedShareDto_11(
                this,
                Invocation.method(#getReceivedShare, [receivedShareId]),
              ),
            ),
          )
          as _i5.Future<_i2.ReceivedShareDto>);

  @override
  _i5.Future<_i2.UploadRequestGroupResponse> addRecipientsToUploadRequestGroup(
    _i6.UploadRequestGroupId? uploadRequestGroupId,
    List<_i6.GenericUser>? recipients,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRecipientsToUploadRequestGroup, [
              uploadRequestGroupId,
              recipients,
            ]),
            returnValue: _i5.Future<_i2.UploadRequestGroupResponse>.value(
              _FakeUploadRequestGroupResponse_9(
                this,
                Invocation.method(#addRecipientsToUploadRequestGroup, [
                  uploadRequestGroupId,
                  recipients,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestGroupResponse>);

  @override
  _i5.Future<_i2.UploadRequestGroupResponse> updateUploadRequestGroupStatus(
    _i6.UploadRequestGroupId? uploadRequestGroupId,
    _i6.UploadRequestStatus? status, {
    bool? copyToMySpace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadRequestGroupStatus,
              [uploadRequestGroupId, status],
              {#copyToMySpace: copyToMySpace},
            ),
            returnValue: _i5.Future<_i2.UploadRequestGroupResponse>.value(
              _FakeUploadRequestGroupResponse_9(
                this,
                Invocation.method(
                  #updateUploadRequestGroupStatus,
                  [uploadRequestGroupId, status],
                  {#copyToMySpace: copyToMySpace},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestGroupResponse>);

  @override
  _i5.Future<List<_i2.AuthenticationAuditLogEntryUserResponse>>
  getAuditAuthenticationEntryUser() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditAuthenticationEntryUser, []),
            returnValue:
                _i5.Future<
                  List<_i2.AuthenticationAuditLogEntryUserResponse>
                >.value(<_i2.AuthenticationAuditLogEntryUserResponse>[]),
          )
          as _i5.Future<List<_i2.AuthenticationAuditLogEntryUserResponse>>);

  @override
  _i5.Future<_i2.WorkGroupNodeDto> moveWorkgroupNode(
    _i2.MoveWorkGroupNodeBodyRequest? moveRequest,
    _i6.SharedSpaceId? sourceSharedSpaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveWorkgroupNode, [
              moveRequest,
              sourceSharedSpaceId,
            ]),
            returnValue: _i5.Future<_i2.WorkGroupNodeDto>.value(
              _FakeWorkGroupNodeDto_3(
                this,
                Invocation.method(#moveWorkgroupNode, [
                  moveRequest,
                  sourceSharedSpaceId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.WorkGroupNodeDto>);

  @override
  _i5.Future<_i2.ReceivedShareDto> removeReceivedShare(_i6.ShareId? shareId) =>
      (super.noSuchMethod(
            Invocation.method(#removeReceivedShare, [shareId]),
            returnValue: _i5.Future<_i2.ReceivedShareDto>.value(
              _FakeReceivedShareDto_11(
                this,
                Invocation.method(#removeReceivedShare, [shareId]),
              ),
            ),
          )
          as _i5.Future<_i2.ReceivedShareDto>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> enableVersioningWorkGroup(
    _i6.SharedSpaceId? sharedSpaceId,
    _i2.EnableVersioningWorkGroupBodyRequest? enableVersioningBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enableVersioningWorkGroup, [
              sharedSpaceId,
              enableVersioningBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#enableVersioningWorkGroup, [
                  sharedSpaceId,
                  enableVersioningBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<List<_i2.WorkGroupNodeDto>> advanceSearchWorkGroupNodes(
    _i6.SharedSpaceId? sharedSpaceId,
    _i6.AdvancedSearchRequest? searchRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#advanceSearchWorkGroupNodes, [
              sharedSpaceId,
              searchRequest,
            ]),
            returnValue: _i5.Future<List<_i2.WorkGroupNodeDto>>.value(
              <_i2.WorkGroupNodeDto>[],
            ),
          )
          as _i5.Future<List<_i2.WorkGroupNodeDto>>);

  @override
  bool validateSearchResult(Map<String, dynamic>? jsonResult) =>
      (super.noSuchMethod(
            Invocation.method(#validateSearchResult, [jsonResult]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<String> getOIDCConfiguration(Uri? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getOIDCConfiguration, [baseUrl]),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getOIDCConfiguration, [baseUrl]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.UploadRequestEntryResponse> removeUploadRequestEntry(
    _i6.UploadRequestEntryId? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeUploadRequestEntry, [entryId]),
            returnValue: _i5.Future<_i2.UploadRequestEntryResponse>.value(
              _FakeUploadRequestEntryResponse_12(
                this,
                Invocation.method(#removeUploadRequestEntry, [entryId]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestEntryResponse>);

  @override
  _i5.Future<_i2.UploadRequestGroupResponse> editUploadRequest(
    _i6.UploadRequestGroupId? uploadRequestGroupId,
    _i6.EditUploadRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editUploadRequest, [
              uploadRequestGroupId,
              request,
            ]),
            returnValue: _i5.Future<_i2.UploadRequestGroupResponse>.value(
              _FakeUploadRequestGroupResponse_9(
                this,
                Invocation.method(#editUploadRequest, [
                  uploadRequestGroupId,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestGroupResponse>);

  @override
  _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>> getAllWorkgroups(
    _i6.SharedSpaceId? parentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkgroups, [parentId]),
            returnValue:
                _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>>.value(
                  <_i2.SharedSpaceNodeNestedResponse>[],
                ),
          )
          as _i5.Future<List<_i2.SharedSpaceNodeNestedResponse>>);

  @override
  _i5.Future<_i2.UploadRequestResponse> getUploadRequest(
    _i6.UploadRequestId? uploadRequestId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadRequest, [uploadRequestId]),
            returnValue: _i5.Future<_i2.UploadRequestResponse>.value(
              _FakeUploadRequestResponse_10(
                this,
                Invocation.method(#getUploadRequest, [uploadRequestId]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestResponse>);

  @override
  _i5.Future<_i2.UploadRequestResponse> editUploadRequestRecipient(
    _i6.UploadRequestId? uploadRequestId,
    _i6.EditUploadRequestRecipient? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editUploadRequestRecipient, [
              uploadRequestId,
              request,
            ]),
            returnValue: _i5.Future<_i2.UploadRequestResponse>.value(
              _FakeUploadRequestResponse_10(
                this,
                Invocation.method(#editUploadRequestRecipient, [
                  uploadRequestId,
                  request,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestResponse>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> createNewDrive(
    _i2.CreateDriveBodyRequest? createDriveBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNewDrive, [createDriveBodyRequest]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#createNewDrive, [createDriveBodyRequest]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.SharedSpaceNodeNestedResponse> createNewWorkSpace(
    _i2.CreateWorkSpaceBodyRequest? createWorkSpaceBodyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNewWorkSpace, [
              createWorkSpaceBodyRequest,
            ]),
            returnValue: _i5.Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5(
                this,
                Invocation.method(#createNewWorkSpace, [
                  createWorkSpaceBodyRequest,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.SharedSpaceNodeNestedResponse>);

  @override
  _i5.Future<_i2.UploadRequestGroupResponse> getUploadRequestGroup(
    _i6.UploadRequestGroupId? uploadRequestGroupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadRequestGroup, [uploadRequestGroupId]),
            returnValue: _i5.Future<_i2.UploadRequestGroupResponse>.value(
              _FakeUploadRequestGroupResponse_9(
                this,
                Invocation.method(#getUploadRequestGroup, [
                  uploadRequestGroupId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadRequestGroupResponse>);

  @override
  _i5.Future<List<_i2.AuditLogEntryUserDto?>> getUploadRequestActivities(
    _i6.UploadRequestId? uploadRequestId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadRequestActivities, [uploadRequestId]),
            returnValue: _i5.Future<List<_i2.AuditLogEntryUserDto?>>.value(
              <_i2.AuditLogEntryUserDto?>[],
            ),
          )
          as _i5.Future<List<_i2.AuditLogEntryUserDto?>>);

  @override
  _i5.Future<List<_i2.AuditLogEntryUserDto?>> getUploadRequestEntryActivities(
    _i6.UploadRequestEntryId? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadRequestEntryActivities, [entryId]),
            returnValue: _i5.Future<List<_i2.AuditLogEntryUserDto?>>.value(
              <_i2.AuditLogEntryUserDto?>[],
            ),
          )
          as _i5.Future<List<_i2.AuditLogEntryUserDto?>>);
}
