// Mocks generated by Mockito from annotations
// in data/test/local/document_database_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:data/src/local/database_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_1 extends _i1.SmartFake implements _i2.Batch {
  _FakeBatch_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseClient extends _i1.Mock implements _i3.DatabaseClient {
  MockDatabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<_i2.Batch> get batch =>
      (super.noSuchMethod(
            Invocation.getter(#batch),
            returnValue: _i4.Future<_i2.Batch>.value(
              _FakeBatch_1(this, Invocation.getter(#batch)),
            ),
          )
          as _i4.Future<_i2.Batch>);

  @override
  _i4.Future<dynamic> closeDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#closeDatabase, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<int> insertData(
    String? tableName,
    Map<String, dynamic>? mapObject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertData, [tableName, mapObject]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteData(String? tableName, String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#deleteData, [tableName, key, value]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateData(
    String? tableName,
    String? key,
    String? value,
    Map<String, dynamic>? mapObject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateData, [tableName, key, value, mapObject]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getData(
    String? tableName,
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [tableName, key, value]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getListData(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#getListData, [tableName]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<dynamic> deleteLocalFile(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalFile, [localPath]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getListDataWithCondition(
    String? tableName,
    String? condition,
    List<dynamic>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getListDataWithCondition, [
              tableName,
              condition,
              values,
            ]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<dynamic> insertMultipleData(
    String? tableName,
    List<Map<String, dynamic>?>? mapObjects,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertMultipleData, [tableName, mapObjects]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<int> clearAllData(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, [tableName]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<dynamic> deleteListFile(List<String>? listLocalPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListFile, [listLocalPath]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
