// Mocks generated by Mockito from annotations
// in domain/test/usecases/quota/get_quota_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountQuota_0 extends _i1.SmartFake implements _i2.AccountQuota {
  _FakeAccountQuota_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuotaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuotaRepository extends _i1.Mock implements _i2.QuotaRepository {
  MockQuotaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.AccountQuota> findQuota(_i2.QuotaId? quotaUuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #findQuota,
          [quotaUuid],
        ),
        returnValue: _i3.Future<_i2.AccountQuota>.value(_FakeAccountQuota_0(
          this,
          Invocation.method(
            #findQuota,
            [quotaUuid],
          ),
        )),
      ) as _i3.Future<_i2.AccountQuota>);

  @override
  _i3.Future<dynamic> saveQuota(_i2.AccountQuota? accountQuota) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveQuota,
          [accountQuota],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i2.AccountQuota> getQuotaOffline() => (super.noSuchMethod(
        Invocation.method(
          #getQuotaOffline,
          [],
        ),
        returnValue: _i3.Future<_i2.AccountQuota>.value(_FakeAccountQuota_0(
          this,
          Invocation.method(
            #getQuotaOffline,
            [],
          ),
        )),
      ) as _i3.Future<_i2.AccountQuota>);
}
