// Mocks generated by Mockito from annotations
// in domain/test/usecases/authentication/get_credential_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeToken_0 extends _i1.SmartFake implements _i2.Token {
  _FakeToken_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenRepository extends _i1.Mock implements _i2.TokenRepository {
  MockTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> persistToken(_i2.Token? token) => (super.noSuchMethod(
        Invocation.method(
          #persistToken,
          [token],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<_i2.Token> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<_i2.Token>.value(_FakeToken_0(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Token>);
}

/// A class which mocks [CredentialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialRepository extends _i1.Mock
    implements _i2.CredentialRepository {
  MockCredentialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> saveBaseUrl(Uri? baseUrl) => (super.noSuchMethod(
        Invocation.method(
          #saveBaseUrl,
          [baseUrl],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> removeBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #removeBaseUrl,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<Uri> getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: _i3.Future<Uri>.value(_FakeUri_1(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
      ) as _i3.Future<Uri>);
}

/// A class which mocks [APIRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIRepository extends _i1.Mock implements _i2.APIRepository {
  MockAPIRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> persistAPIVersionSupported(
          _i2.APIVersionSupported? apiVersionSupported) =>
      (super.noSuchMethod(
        Invocation.method(
          #persistAPIVersionSupported,
          [apiVersionSupported],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.APIVersionSupported> getAPIVersionSupported() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAPIVersionSupported,
          [],
        ),
        returnValue: _i3.Future<_i2.APIVersionSupported>.value(
            _i2.APIVersionSupported.v5),
      ) as _i3.Future<_i2.APIVersionSupported>);
}
