// Mocks generated by Mockito from annotations
// in domain/test/usecases/autocomplete/get_autocomplete_sharing_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AutoCompleteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoCompleteRepository extends _i1.Mock
    implements _i2.AutoCompleteRepository {
  MockAutoCompleteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.AutoCompleteResult>> getAutoComplete(
    _i2.AutoCompletePattern? autoCompletePattern,
    _i2.AutoCompleteType? autoCompleteType, {
    _i2.ThreadId? threadId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutoComplete,
          [
            autoCompletePattern,
            autoCompleteType,
          ],
          {#threadId: threadId},
        ),
        returnValue: _i3.Future<List<_i2.AutoCompleteResult>>.value(
            <_i2.AutoCompleteResult>[]),
      ) as _i3.Future<List<_i2.AutoCompleteResult>>);
}
