// Mocks generated by Mockito from annotations
// in domain/test/usecases/myspace/copy_multiple_files_to_my_space_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlowFile_0 extends _i1.SmartFake implements _i2.FlowFile {
  _FakeFlowFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_1 extends _i1.SmartFake implements _i2.Document {
  _FakeDocument_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentDetails_2 extends _i1.SmartFake
    implements _i2.DocumentDetails {
  _FakeDocumentDetails_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i2.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlowFile uploadChunks(_i2.FileInfo? fileInfo) => (super.noSuchMethod(
        Invocation.method(
          #uploadChunks,
          [fileInfo],
        ),
        returnValue: _FakeFlowFile_0(
          this,
          Invocation.method(
            #uploadChunks,
            [fileInfo],
          ),
        ),
      ) as _i2.FlowFile);

  @override
  _i3.Future<List<_i2.Document>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i3.Future<List<_i2.Document>>);

  @override
  _i3.Future<List<_i2.DownloadTaskId>> downloadDocuments(
    List<_i2.DocumentId>? documentIds,
    _i2.Token? token,
    Uri? baseUrl,
    _i2.APIVersionSupported? apiVersion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDocuments,
          [
            documentIds,
            token,
            baseUrl,
            apiVersion,
          ],
        ),
        returnValue:
            _i3.Future<List<_i2.DownloadTaskId>>.value(<_i2.DownloadTaskId>[]),
      ) as _i3.Future<List<_i2.DownloadTaskId>>);

  @override
  _i3.Future<List<_i2.Share>> share(
    List<_i2.DocumentId>? documentIds,
    List<_i2.MailingListId>? mailingListIds,
    List<_i2.GenericUser>? recipients,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #share,
          [
            documentIds,
            mailingListIds,
            recipients,
          ],
        ),
        returnValue: _i3.Future<List<_i2.Share>>.value(<_i2.Share>[]),
      ) as _i3.Future<List<_i2.Share>>);

  @override
  _i3.Future<String> downloadDocumentIOS(
    _i2.Document? document,
    _i2.Token? token,
    Uri? baseUrl,
    _i4.CancelToken? cancelToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDocumentIOS,
          [
            document,
            token,
            baseUrl,
            cancelToken,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #downloadDocumentIOS,
            [
              document,
              token,
              baseUrl,
              cancelToken,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i2.Document> remove(_i2.DocumentId? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [documentId],
        ),
        returnValue: _i3.Future<_i2.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #remove,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i2.Document>);

  @override
  _i3.Future<_i2.Document> rename(
    _i2.DocumentId? documentId,
    _i2.RenameDocumentRequest? renameDocumentRequest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rename,
          [
            documentId,
            renameDocumentRequest,
          ],
        ),
        returnValue: _i3.Future<_i2.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #rename,
            [
              documentId,
              renameDocumentRequest,
            ],
          ),
        )),
      ) as _i3.Future<_i2.Document>);

  @override
  _i3.Future<List<_i2.Document>> copyToMySpace(_i2.CopyRequest? copyRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyToMySpace,
          [copyRequest],
        ),
        returnValue: _i3.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i3.Future<List<_i2.Document>>);

  @override
  _i3.Future<String> downloadPreviewDocument(
    _i2.Document? document,
    _i2.DownloadPreviewType? downloadPreviewType,
    _i2.Token? token,
    Uri? baseUrl,
    _i4.CancelToken? cancelToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadPreviewDocument,
          [
            document,
            downloadPreviewType,
            token,
            baseUrl,
            cancelToken,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #downloadPreviewDocument,
            [
              document,
              downloadPreviewType,
              token,
              baseUrl,
              cancelToken,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i2.DocumentDetails> getDocument(_i2.DocumentId? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [documentId],
        ),
        returnValue:
            _i3.Future<_i2.DocumentDetails>.value(_FakeDocumentDetails_2(
          this,
          Invocation.method(
            #getDocument,
            [documentId],
          ),
        )),
      ) as _i3.Future<_i2.DocumentDetails>);

  @override
  _i3.Future<_i2.Document> editDescription(
    _i2.DocumentId? documentId,
    _i2.EditDescriptionDocumentRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editDescription,
          [
            documentId,
            request,
          ],
        ),
        returnValue: _i3.Future<_i2.Document>.value(_FakeDocument_1(
          this,
          Invocation.method(
            #editDescription,
            [
              documentId,
              request,
            ],
          ),
        )),
      ) as _i3.Future<_i2.Document>);

  @override
  _i3.Future<_i2.Document?> getDocumentOffline(_i2.DocumentId? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentOffline,
          [documentId],
        ),
        returnValue: _i3.Future<_i2.Document?>.value(),
      ) as _i3.Future<_i2.Document?>);

  @override
  _i3.Future<bool> updateDocumentOffline(
    _i2.Document? document,
    String? localPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentOffline,
          [
            document,
            localPath,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> makeAvailableOffline(
    _i2.Document? document,
    String? localPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeAvailableOffline,
          [
            document,
            localPath,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> disableAvailableOffline(
    _i2.DocumentId? documentId,
    String? localPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #disableAvailableOffline,
          [
            documentId,
            localPath,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i2.Document>> getAllDocumentOffline() => (super.noSuchMethod(
        Invocation.method(
          #getAllDocumentOffline,
          [],
        ),
        returnValue: _i3.Future<List<_i2.Document>>.value(<_i2.Document>[]),
      ) as _i3.Future<List<_i2.Document>>);

  @override
  _i3.Future<String> downloadMakeOfflineDocument(
    _i2.DocumentId? documentId,
    String? documentName,
    _i2.DownloadPreviewType? downloadPreviewType,
    _i2.Token? permanentToken,
    Uri? baseUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMakeOfflineDocument,
          [
            documentId,
            documentName,
            downloadPreviewType,
            permanentToken,
            baseUrl,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #downloadMakeOfflineDocument,
            [
              documentId,
              documentName,
              downloadPreviewType,
              permanentToken,
              baseUrl,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
