// Mocks generated by Mockito from annotations
// in domain/test/usecases/upload_request_entry/get_all_upload_request_entry_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUploadRequestEntry_0 extends _i1.SmartFake
    implements _i2.UploadRequestEntry {
  _FakeUploadRequestEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UploadRequestEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRequestEntryRepository extends _i1.Mock
    implements _i2.UploadRequestEntryRepository {
  MockUploadRequestEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.UploadRequestEntry>> getAllUploadRequestEntries(
          _i2.UploadRequestId? uploadRequestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUploadRequestEntries,
          [uploadRequestId],
        ),
        returnValue: _i3.Future<List<_i2.UploadRequestEntry>>.value(
            <_i2.UploadRequestEntry>[]),
      ) as _i3.Future<List<_i2.UploadRequestEntry>>);

  @override
  _i3.Future<List<_i2.DownloadTaskId>> downloadUploadRequestEntries(
    List<_i2.UploadRequestEntry>? uploadRequestEntry,
    _i2.Token? token,
    Uri? baseUrl,
    _i2.APIVersionSupported? apiVersion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUploadRequestEntries,
          [
            uploadRequestEntry,
            token,
            baseUrl,
            apiVersion,
          ],
        ),
        returnValue:
            _i3.Future<List<_i2.DownloadTaskId>>.value(<_i2.DownloadTaskId>[]),
      ) as _i3.Future<List<_i2.DownloadTaskId>>);

  @override
  _i3.Future<String> downloadUploadRequestEntryIOS(
    _i2.UploadRequestEntry? uploadRequestEntry,
    _i2.Token? token,
    Uri? baseUrl,
    _i4.CancelToken? cancelToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUploadRequestEntryIOS,
          [
            uploadRequestEntry,
            token,
            baseUrl,
            cancelToken,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #downloadUploadRequestEntryIOS,
            [
              uploadRequestEntry,
              token,
              baseUrl,
              cancelToken,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i2.UploadRequestEntry> removeUploadRequestEntry(
          _i2.UploadRequestEntryId? entryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUploadRequestEntry,
          [entryId],
        ),
        returnValue:
            _i3.Future<_i2.UploadRequestEntry>.value(_FakeUploadRequestEntry_0(
          this,
          Invocation.method(
            #removeUploadRequestEntry,
            [entryId],
          ),
        )),
      ) as _i3.Future<_i2.UploadRequestEntry>);

  @override
  _i3.Future<List<_i2.AuditLogEntryUser?>> getUploadRequestEntryActivities(
          _i2.UploadRequestEntryId? entryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadRequestEntryActivities,
          [entryId],
        ),
        returnValue: _i3.Future<List<_i2.AuditLogEntryUser?>>.value(
            <_i2.AuditLogEntryUser?>[]),
      ) as _i3.Future<List<_i2.AuditLogEntryUser?>>);
}
